"""Increased some fields length

Revision ID: 9ad9649de8f3
Revises: f9631f5ef14d
Create Date: 2025-07-14 12:01:09.241013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad9649de8f3'
down_revision: Union[str, Sequence[str], None] = 'f9631f5ef14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spimex_trading_results', 'exchange_product_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'exchange_product_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'oil_id',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_basis_id',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_basis_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_type_id',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spimex_trading_results', 'delivery_type_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_basis_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_basis_id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'oil_id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'exchange_product_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('spimex_trading_results', 'exchange_product_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
