"""Initial revision

Revision ID: f9631f5ef14d
Revises: 
Create Date: 2025-07-14 11:17:54.813133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9631f5ef14d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_product_id', sa.String(length=10), nullable=True),
    sa.Column('exchange_product_name', sa.String(length=255), nullable=True),
    sa.Column('oil_id', sa.String(length=4), nullable=True),
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=True),
    sa.Column('delivery_basis_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spimex_trading_results_date'), 'spimex_trading_results', ['date'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_delivery_basis_id'), 'spimex_trading_results', ['delivery_basis_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_exchange_product_id'), 'spimex_trading_results', ['exchange_product_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_id'), 'spimex_trading_results', ['id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_oil_id'), 'spimex_trading_results', ['oil_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spimex_trading_results_oil_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_exchange_product_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_delivery_basis_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_date'), table_name='spimex_trading_results')
    op.drop_table('spimex_trading_results')
    # ### end Alembic commands ###
